# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:

- main

pool:
  name: LiquidInitSelfPool

steps:
- task: Bash@3

  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo '$(Build.BinariesDirectory)'
      echo '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'tar'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: Bash@3
  inputs:
    filePath: '/azure/apps/repackdist.sh'
    arguments: '$(Build.BinariesDirectory)/$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'